# SPDX-FileCopyrightText: 2025-2026 Ryo Zen (https://github.com/ryo-zen)
# SPDX-License-Identifier: GPL-3.0-only

name: Ocelot Wallet
key: OCELO
icon: 🔥
ticket_counter: 9
created: 2026-03-13T23:45:34.636806867+00:00
